// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 259 1 0 "f434a8b8_7218_4d54_b78c4a881731a3d0" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar10ulLowVolumeTipWithFilter, Translate("10uL_Tips"), ML_STAR);
// }} ""
// {{{ 260 1 0 "1741a794_ca8d_4482_a30e22237e0254dc" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, Translate("300uL_Tips"), ML_STAR);
// }} ""
// {{{ 261 1 0 "ca525f6f_715c_471c_ab382715e216e897" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar50ulTipWithFilter, Translate("50uL_Tips"), ML_STAR);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2021-11-23 11:09$$checksum=3697dbcc$$length=087$$